// =====================================================================
// historical-record-pdf.service.js — v3.4.3
// Generate a professional EMR PDF for a Historical Record (same
// architecture as Prescriptions / Medical Certificates).
// =====================================================================
const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const STORAGE_PATH = process.env.STORAGE_PATH || path.join(process.cwd(), 'storage');
const OUT_DIR = path.join(STORAGE_PATH, 'historical-pdf');
function ensureDir(p){ if (!fs.existsSync(p)) fs.mkdirSync(p, { recursive: true }); }

function humanType(t){
  const m = { LAB_REPORT:'Lab Report', CONSULTATION:'Consultation', RADIOLOGY:'Radiology / Imaging', PRESCRIPTION:'Prescription', VACCINATION:'Vaccination', DISCHARGE:'Discharge Summary', OTHER:'Other' };
  return m[t] || t || 'General Record';
}
function fmt(d){ if(!d) return '—'; const x = new Date(d); return x.toLocaleDateString('en-GB', { day:'2-digit', month:'short', year:'numeric' }); }

async function generateHistoricalRecordPdf(record){
  ensureDir(OUT_DIR);
  const filename = `historical-record-${record.id}.pdf`;
  const outPath = path.join(OUT_DIR, filename);
  const publicUrl = `/files/historical-pdf/${filename}`;

  await new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const stream = fs.createWriteStream(outPath);
    doc.pipe(stream);

    const L = 50, W = 495;
    doc.fontSize(18).font('Helvetica-Bold').text('NeoKidsPro — Historical Medical Record', L, 50);
    doc.moveTo(L, 78).lineTo(L+W, 78).lineWidth(1).stroke('#333');

    doc.fontSize(10).font('Helvetica');
    let y = 95;
    const row = (k, v) => { doc.font('Helvetica-Bold').text(k, L, y, { width: 140 }); doc.font('Helvetica').text(String(v || '—'), L+145, y, { width: W-145 }); y = doc.y + 4; };

    row('Patient:', record.patient ? record.patient.name : '');
    row('Record Title:', record.title || humanType(record.recordType));
    row('Record Type:', humanType(record.recordType));
    row('Record Date:', fmt(record.recordDate));
    row('Recorded By:', record.doctor ? 'Dr. ' + record.doctor.name : '');
    row('Generated:', fmt(new Date()));

    y += 6; doc.moveTo(L, y).lineTo(L+W, y).stroke('#999'); y += 10;
    const section = (title, body) => {
      if (!body) return;
      if (y > 720) { doc.addPage(); y = 50; }
      doc.font('Helvetica-Bold').fontSize(11).text(title, L, y); y = doc.y + 2;
      doc.font('Helvetica').fontSize(10).text(body, L, y, { width: W }); y = doc.y + 10;
    };
    section('Diagnosis', record.diagnosis);
    section('Clinical Notes', record.notes);
    section('Treatment Given', record.treatment);
    section('Medications', record.medications);

    if (record.attachments && record.attachments.length){
      if (y > 700) { doc.addPage(); y = 50; }
      doc.font('Helvetica-Bold').fontSize(11).text('Attachments', L, y); y = doc.y + 4;
      record.attachments.forEach((a, i) => {
        doc.font('Helvetica').fontSize(10).text(`${i+1}. ${a.label || a.originalName} (${a.kind || 'file'})`, L+12, y, { width: W-12 });
        y = doc.y + 2;
      });
    }

    doc.fontSize(8).fillColor('#777').text('Generated by NeoKidsPro EMR. This document summarises a historical/external record uploaded to the patient timeline.', L, 780, { width: W, align: 'center' });
    doc.end();
    stream.on('finish', resolve);
    stream.on('error', reject);
  });

  return { absolutePath: outPath, publicUrl, filename };
}

module.exports = { generateHistoricalRecordPdf, humanType };
