const { createPasswordToken, revokeActivePasswordTokens } = require('./token.service');
const { _helpers: authHelpers } = require('../controllers/auth.controller');
const whatsapp = require('./whatsapp.service');
const prisma = require('../config/prisma');
const logger = require('../utils/logger');

// Invite links are generated by an admin for someone who may not open
// their inbox right away (a new doctor, receptionist or pharmacy hire),
// so they get a much longer window than a self-triggered password reset.
const INVITE_TOKEN_TTL_MINUTES = parseInt(process.env.INVITE_TOKEN_TTL_MINUTES || '1440', 10);
const WA_TPL_STAFF_INVITE = process.env.WA_TPL_STAFF_INVITE || 'neokids_staff_invite_v1';

function formatTtl(minutes) {
  if (minutes % 1440 === 0) {
    const days = minutes / 1440;
    return `${days} day${days === 1 ? '' : 's'}`;
  }
  if (minutes % 60 === 0) {
    const hours = minutes / 60;
    return `${hours} hour${hours === 1 ? '' : 's'}`;
  }
  return `${minutes} minutes`;
}

// Issues a fresh INVITE token, revoking any still-active INVITE/RESET
// token for the account first. Shared by both delivery channels below so
// "resend" always means exactly one usable link, regardless of channel.
async function issueInviteToken(userType, userId) {
  await revokeActivePasswordTokens(userType, userId, ['INVITE', 'RESET']);
  return createPasswordToken({
    userType, userId, purpose: 'INVITE', expiresInMinutes: INVITE_TOKEN_TTL_MINUTES
  });
}

// Creates (or replaces) an INVITE token for a staff account and emails it.
// Used both for the first invite and for an admin-triggered resend —
// callers decide when this runs; account creation never calls it directly.
async function sendStaffInvite({ user, userType, roleLabel }) {
  const { rawToken } = await issueInviteToken(userType, user.id);

  let inviteLink;
  let emailDelivered = false;
  try {
    inviteLink = await authHelpers.sendPasswordEmail({
      to: user.email, name: user.name, rawToken, purpose: 'INVITE', expiresInMinutes: INVITE_TOKEN_TTL_MINUTES
    });
    emailDelivered = !!process.env.SMTP_HOST;
  } catch (e) {
    logger.error(`${roleLabel} invite email failed`, e);
    inviteLink = authHelpers.buildPasswordLink(rawToken);
  }
  return { inviteLink, emailDelivered, expiresInMinutes: INVITE_TOKEN_TTL_MINUTES };
}

// Same invite flow as sendStaffInvite, delivered over WhatsApp instead of
// email. Issues its own fresh token — sending on one channel invalidates
// any link already sent on the other, so there is only ever one live link.
async function sendStaffInviteWhatsApp({ user, userType, roleLabel }) {
  if (!user.phone) {
    throw Object.assign(new Error(`${roleLabel} has no phone number on file`), { code: 'NO_PHONE' });
  }

  const { rawToken } = await issueInviteToken(userType, user.id);
  const inviteLink = authHelpers.buildPasswordLink(rawToken);
  const ttlLabel = formatTtl(INVITE_TOKEN_TTL_MINUTES);

  const result = await whatsapp.sendWhatsAppWithFallback({
    to: user.phone,
    primaryTemplate: WA_TPL_STAFF_INVITE,
    fallbackTemplate: null,
    bodyParams: [user.name, roleLabel, ttlLabel],
    urlButtonParam: rawToken,
    plainTextFallback:
      `Hi ${user.name}, you've been added as a ${roleLabel} on NeoKidsPro. ` +
      `Set your password to activate your account: ${inviteLink} (link expires in ${ttlLabel}). — NeoKidsPro`
  });

  await prisma.notificationLog.create({
    data: {
      appointmentId: null,
      channel: 'WHATSAPP',
      recipient: user.phone,
      template: WA_TPL_STAFF_INVITE,
      direction: roleLabel.toUpperCase(),
      status: result.ok ? 'SENT' : 'FAILED',
      payload: result.ok ? (result.response || { via: result.via }) : undefined,
      errorMessage: result.ok ? null : (result.error && result.error.message) || 'WhatsApp invite failed'
    }
  }).catch((e) => logger.error('Failed to log invite WhatsApp notification', e));

  if (!result.ok) {
    throw Object.assign(new Error((result.error && result.error.message) || 'WhatsApp invite failed to send'), {
      code: 'WA_SEND_FAILED', detail: result.error, inviteLink, expiresInMinutes: INVITE_TOKEN_TTL_MINUTES
    });
  }

  return { inviteLink, expiresInMinutes: INVITE_TOKEN_TTL_MINUTES, via: result.via };
}

module.exports = { sendStaffInvite, sendStaffInviteWhatsApp, INVITE_TOKEN_TTL_MINUTES };
