const { createPasswordToken, revokeActivePasswordTokens } = require('./token.service');
const { _helpers: authHelpers } = require('../controllers/auth.controller');

// Invite links are generated by an admin for someone who may not open
// their inbox right away (a new doctor, receptionist or pharmacy hire),
// so they get a much longer window than a self-triggered password reset.
const INVITE_TOKEN_TTL_MINUTES = parseInt(process.env.INVITE_TOKEN_TTL_MINUTES || '1440', 10);

// Creates (or replaces) an INVITE token for a staff account and emails it.
// Used both for the first invite and for an admin-triggered resend —
// callers decide when this runs; account creation never calls it directly.
async function sendStaffInvite({ user, userType, roleLabel }) {
  await revokeActivePasswordTokens(userType, user.id, ['INVITE', 'RESET']);
  const { rawToken } = await createPasswordToken({
    userType, userId: user.id, purpose: 'INVITE', expiresInMinutes: INVITE_TOKEN_TTL_MINUTES
  });

  let inviteLink;
  let emailDelivered = false;
  try {
    inviteLink = await authHelpers.sendPasswordEmail({
      to: user.email, name: user.name, rawToken, purpose: 'INVITE', expiresInMinutes: INVITE_TOKEN_TTL_MINUTES
    });
    emailDelivered = !!process.env.SMTP_HOST;
  } catch (e) {
    console.error(`${roleLabel} invite email failed:`, e.message);
    inviteLink = authHelpers.buildPasswordLink(rawToken);
  }
  return { inviteLink, emailDelivered, expiresInMinutes: INVITE_TOKEN_TTL_MINUTES };
}

module.exports = { sendStaffInvite, INVITE_TOKEN_TTL_MINUTES };
